apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cryptochords-api-deployment.yaml
  - cryptochords-api-service.yaml
  - cryptochords-web-deployment.yaml
  - cryptochords-web-service.yaml
  - cryptochords-web-ingress.yaml
